'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WPFFootball.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arizona_Cardinals_Helmet.jpg.
        '''</summary>
        Friend ReadOnly Property Arizona_Cardinals_HelmetJpg() As String
            Get
                Return ResourceManager.GetString("Arizona_Cardinals_HelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arizona_Cardinals.jpg.
        '''</summary>
        Friend ReadOnly Property Arizona_CardinalsJpg() As String
            Get
                Return ResourceManager.GetString("Arizona_CardinalsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArizonaCardinals3.jpg.
        '''</summary>
        Friend ReadOnly Property ArizonaCardinals3Jpg() As String
            Get
                Return ResourceManager.GetString("ArizonaCardinals3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArrowheadStadium.jpg.
        '''</summary>
        Friend ReadOnly Property ArrowheadStadiumJpg() As String
            Get
                Return ResourceManager.GetString("ArrowheadStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atlanta_Falcons_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Atlanta_Falcons_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Atlanta_Falcons_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atlanta_Falcons.jpg.
        '''</summary>
        Friend ReadOnly Property Atlanta_FalconsJpg() As String
            Get
                Return ResourceManager.GetString("Atlanta_FalconsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATTStadium.jpg.
        '''</summary>
        Friend ReadOnly Property ATTStadiumJpg() As String
            Get
                Return ResourceManager.GetString("ATTStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baltimore_Ravens_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Baltimore_Ravens_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Baltimore_Ravens_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baltimore_Ravens3.jpg.
        '''</summary>
        Friend ReadOnly Property Baltimore_Ravens3Jpg() As String
            Get
                Return ResourceManager.GetString("Baltimore_Ravens3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BankOfAmericaStadium.jpg.
        '''</summary>
        Friend ReadOnly Property BankOfAmericaStadiumJpg() As String
            Get
                Return ResourceManager.GetString("BankOfAmericaStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffalo_Bills_PHelmet_2011.jpg.
        '''</summary>
        Friend ReadOnly Property Buffalo_Bills_PHelmet_2011Jpg() As String
            Get
                Return ResourceManager.GetString("Buffalo_Bills_PHelmet_2011Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffalo_Bills02.jpg.
        '''</summary>
        Friend ReadOnly Property Buffalo_Bills02Jpg() As String
            Get
                Return ResourceManager.GetString("Buffalo_Bills02Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carolina_Panthers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Carolina_Panthers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Carolina_Panthers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carolina_Panthers2.jpg.
        '''</summary>
        Friend ReadOnly Property Carolina_Panthers2Jpg() As String
            Get
                Return ResourceManager.GetString("Carolina_Panthers2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carolina_Panthers.jpg.
        '''</summary>
        Friend ReadOnly Property Carolina_PanthersJpg() As String
            Get
                Return ResourceManager.GetString("Carolina_PanthersJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CenturyLinkField.jpg.
        '''</summary>
        Friend ReadOnly Property CenturyLinkFieldJpg() As String
            Get
                Return ResourceManager.GetString("CenturyLinkFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chicago_Bears_PHelmet2.jpg.
        '''</summary>
        Friend ReadOnly Property Chicago_Bears_PHelmet2Jpg() As String
            Get
                Return ResourceManager.GetString("Chicago_Bears_PHelmet2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chicago_Bears4.jpg.
        '''</summary>
        Friend ReadOnly Property Chicago_Bears4Jpg() As String
            Get
                Return ResourceManager.GetString("Chicago_Bears4Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cincinnati_Bengals_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Cincinnati_Bengals_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Cincinnati_Bengals_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cincinnati_Bengals3.jpg.
        '''</summary>
        Friend ReadOnly Property Cincinnati_Bengals3Jpg() As String
            Get
                Return ResourceManager.GetString("Cincinnati_Bengals3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleveland_Browns_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Cleveland_Browns_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Cleveland_Browns_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleveland_Browns2.jpg.
        '''</summary>
        Friend ReadOnly Property Cleveland_Browns2Jpg() As String
            Get
                Return ResourceManager.GetString("Cleveland_Browns2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleveland_Browns2.jpg.
        '''</summary>
        Friend ReadOnly Property Cleveland_Browns2Jpg1() As String
            Get
                Return ResourceManager.GetString("Cleveland_Browns2Jpg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ClevelandBrowns2.jpg.
        '''</summary>
        Friend ReadOnly Property ClevelandBrowns2Jpg() As String
            Get
                Return ResourceManager.GetString("ClevelandBrowns2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dallas_Cowboys_Phelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Dallas_Cowboys_PhelmetJpg() As String
            Get
                Return ResourceManager.GetString("Dallas_Cowboys_PhelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dallas_Cowboys3.jpg.
        '''</summary>
        Friend ReadOnly Property Dallas_Cowboys3Jpg() As String
            Get
                Return ResourceManager.GetString("Dallas_Cowboys3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denver_Broncos_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Denver_Broncos_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Denver_Broncos_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denver_Broncos2.jpg.
        '''</summary>
        Friend ReadOnly Property Denver_Broncos2Jpg() As String
            Get
                Return ResourceManager.GetString("Denver_Broncos2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detroit_Lions_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Detroit_Lions_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Detroit_Lions_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detroit_Lions3a.jpg.
        '''</summary>
        Friend ReadOnly Property Detroit_Lions3aJpg() As String
            Get
                Return ResourceManager.GetString("Detroit_Lions3aJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DetroitLions2.jpg.
        '''</summary>
        Friend ReadOnly Property DetroitLions2Jpg() As String
            Get
                Return ResourceManager.GetString("DetroitLions2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EverBankField.jpg.
        '''</summary>
        Friend ReadOnly Property EverBankFieldJpg() As String
            Get
                Return ResourceManager.GetString("EverBankFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fedex-field.jpg.
        '''</summary>
        Friend ReadOnly Property FedexFieldJpg() As String
            Get
                Return ResourceManager.GetString("FedexFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FirstEnergyStadium.jpg.
        '''</summary>
        Friend ReadOnly Property FirstEnergyStadiumJpg() As String
            Get
                Return ResourceManager.GetString("FirstEnergyStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fordfield.jpg.
        '''</summary>
        Friend ReadOnly Property FordfieldJpg() As String
            Get
                Return ResourceManager.GetString("FordfieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Georgia-Dome.png.
        '''</summary>
        Friend ReadOnly Property GeorgiaDomePng() As String
            Get
                Return ResourceManager.GetString("GeorgiaDomePng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gillette-stadium.jpg.
        '''</summary>
        Friend ReadOnly Property GilletteStadiumJpg() As String
            Get
                Return ResourceManager.GetString("GilletteStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FootballGoalLine.jpg.
        '''</summary>
        Friend ReadOnly Property GlobalClass_GetBackgroundFilePath_FootballGoalLine_jpg() As String
            Get
                Return ResourceManager.GetString("GlobalClass_GetBackgroundFilePath_FootballGoalLine_jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Green_Bay_Packers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Green_Bay_Packers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Green_Bay_Packers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Green_Bay_Packers5.jpg.
        '''</summary>
        Friend ReadOnly Property Green_Bay_Packers5Jpg() As String
            Get
                Return ResourceManager.GetString("Green_Bay_Packers5Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HeinzField.jpg.
        '''</summary>
        Friend ReadOnly Property HeinzFieldJpg() As String
            Get
                Return ResourceManager.GetString("HeinzFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Houston_Texans_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Houston_Texans_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Houston_Texans_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Houston_Texans2.jpg.
        '''</summary>
        Friend ReadOnly Property Houston_Texans2Jpg() As String
            Get
                Return ResourceManager.GetString("Houston_Texans2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indianapolis_Colts_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Indianapolis_Colts_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Indianapolis_Colts_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indianapolis_Colts2.jpg.
        '''</summary>
        Friend ReadOnly Property Indianapolis_Colts2Jpg() As String
            Get
                Return ResourceManager.GetString("Indianapolis_Colts2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indianapolis_Colts.jpg.
        '''</summary>
        Friend ReadOnly Property Indianapolis_ColtsJpg() As String
            Get
                Return ResourceManager.GetString("Indianapolis_ColtsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jacksonville_Jaguars_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Jacksonville_Jaguars_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Jacksonville_Jaguars_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jacksonville_Jaguars2.jpg.
        '''</summary>
        Friend ReadOnly Property Jacksonville_Jaguars2Jpg() As String
            Get
                Return ResourceManager.GetString("Jacksonville_Jaguars2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kansas_City_Chiefs_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Kansas_City_Chiefs_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Kansas_City_Chiefs_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kansas_City_Chiefs3.jpg.
        '''</summary>
        Friend ReadOnly Property Kansas_City_Chiefs3Jpg() As String
            Get
                Return ResourceManager.GetString("Kansas_City_Chiefs3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to lambeaufield.jpg.
        '''</summary>
        Friend ReadOnly Property LambeaufieldJpg() As String
            Get
                Return ResourceManager.GetString("LambeaufieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LARams1.png.
        '''</summary>
        Friend ReadOnly Property LARams1Png() As String
            Get
                Return ResourceManager.GetString("LARams1Png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LARams.jpg.
        '''</summary>
        Friend ReadOnly Property LARamsJpg() As String
            Get
                Return ResourceManager.GetString("LARamsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to levis-stadium.jpg.
        '''</summary>
        Friend ReadOnly Property LevisStadiumJpg() As String
            Get
                Return ResourceManager.GetString("LevisStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LincolnFinancialField.jpg.
        '''</summary>
        Friend ReadOnly Property LincolnFinancialFieldJpg() As String
            Get
                Return ResourceManager.GetString("LincolnFinancialFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LosAngelesColiseum.jpg.
        '''</summary>
        Friend ReadOnly Property LosAngelesColiseumJpg() As String
            Get
                Return ResourceManager.GetString("LosAngelesColiseumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LucasOilStadium.jpg.
        '''</summary>
        Friend ReadOnly Property LucasOilStadiumJpg() As String
            Get
                Return ResourceManager.GetString("LucasOilStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MetLife_Stadium.jpg.
        '''</summary>
        Friend ReadOnly Property MetLife_StadiumJpg() As String
            Get
                Return ResourceManager.GetString("MetLife_StadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miami_Dolphins_2013.jpg.
        '''</summary>
        Friend ReadOnly Property Miami_Dolphins_2013Jpg() As String
            Get
                Return ResourceManager.GetString("Miami_Dolphins_2013Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miami_Dolphins_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Miami_Dolphins_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Miami_Dolphins_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minnesota_Vikings_2013_06.jpg.
        '''</summary>
        Friend ReadOnly Property Minnesota_Vikings_2013_06Jpg() As String
            Get
                Return ResourceManager.GetString("Minnesota_Vikings_2013_06Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minnesota_Vikings_PHelmet_2013.jpg.
        '''</summary>
        Friend ReadOnly Property Minnesota_Vikings_PHelmet_2013Jpg() As String
            Get
                Return ResourceManager.GetString("Minnesota_Vikings_PHelmet_2013Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M&amp;TBankStadium.jpg.
        '''</summary>
        Friend ReadOnly Property MTBankStadiumJpg() As String
            Get
                Return ResourceManager.GetString("MTBankStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_England_Patriots_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property New_England_Patriots_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("New_England_Patriots_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_England_Patriots2.jpg.
        '''</summary>
        Friend ReadOnly Property New_England_Patriots2Jpg() As String
            Get
                Return ResourceManager.GetString("New_England_Patriots2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_Orleans_Saints_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property New_Orleans_Saints_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("New_Orleans_Saints_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_Orleans_Saints2.jpg.
        '''</summary>
        Friend ReadOnly Property New_Orleans_Saints2Jpg() As String
            Get
                Return ResourceManager.GetString("New_Orleans_Saints2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_Orleans_Saints.jpg.
        '''</summary>
        Friend ReadOnly Property New_Orleans_SaintsJpg() As String
            Get
                Return ResourceManager.GetString("New_Orleans_SaintsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Giants_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property New_York_Giants_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("New_York_Giants_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Giants5.jpg.
        '''</summary>
        Friend ReadOnly Property New_York_Giants5Jpg() As String
            Get
                Return ResourceManager.GetString("New_York_Giants5Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Jets_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property New_York_Jets_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("New_York_Jets_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Jets.jpg.
        '''</summary>
        Friend ReadOnly Property New_York_JetsJpg() As String
            Get
                Return ResourceManager.GetString("New_York_JetsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NissanStadium.jpg.
        '''</summary>
        Friend ReadOnly Property NissanStadiumJpg() As String
            Get
                Return ResourceManager.GetString("NissanStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NRGStadium.jpg.
        '''</summary>
        Friend ReadOnly Property NRGStadiumJpg() As String
            Get
                Return ResourceManager.GetString("NRGStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oakland_Raiders_Helmet.jpg.
        '''</summary>
        Friend ReadOnly Property Oakland_Raiders_HelmetJpg() As String
            Get
                Return ResourceManager.GetString("Oakland_Raiders_HelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oakland_Raiders_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Oakland_Raiders_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Oakland_Raiders_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oakland_Raiders.jpg.
        '''</summary>
        Friend ReadOnly Property Oakland_RaidersJpg() As String
            Get
                Return ResourceManager.GetString("Oakland_RaidersJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OaklandColiseum.jpg.
        '''</summary>
        Friend ReadOnly Property OaklandColiseumJpg() As String
            Get
                Return ResourceManager.GetString("OaklandColiseumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PaulBrownStadium.jpg.
        '''</summary>
        Friend ReadOnly Property PaulBrownStadiumJpg() As String
            Get
                Return ResourceManager.GetString("PaulBrownStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Philadelphia_Eagles_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Philadelphia_Eagles_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Philadelphia_Eagles_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Philadelphia_Eagles2.jpg.
        '''</summary>
        Friend ReadOnly Property Philadelphia_Eagles2Jpg() As String
            Get
                Return ResourceManager.GetString("Philadelphia_Eagles2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pittsburgh_Steelers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Pittsburgh_Steelers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Pittsburgh_Steelers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pittsburgh_Steelers2.jpg.
        '''</summary>
        Friend ReadOnly Property Pittsburgh_Steelers2Jpg() As String
            Get
                Return ResourceManager.GetString("Pittsburgh_Steelers2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pittsburgh_Steelers.jpg.
        '''</summary>
        Friend ReadOnly Property Pittsburgh_SteelersJpg() As String
            Get
                Return ResourceManager.GetString("Pittsburgh_SteelersJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QualcommStadium.jpg.
        '''</summary>
        Friend ReadOnly Property QualcommStadiumJpg() As String
            Get
                Return ResourceManager.GetString("QualcommStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RalphWilsonStadium.jpg.
        '''</summary>
        Friend ReadOnly Property RalphWilsonStadiumJpg() As String
            Get
                Return ResourceManager.GetString("RalphWilsonStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RaymondJamesStadium.jpg.
        '''</summary>
        Friend ReadOnly Property RaymondJamesStadiumJpg() As String
            Get
                Return ResourceManager.GetString("RaymondJamesStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Diego_Chargers_PHelmet2.jpg.
        '''</summary>
        Friend ReadOnly Property San_Diego_Chargers_PHelmet2Jpg() As String
            Get
                Return ResourceManager.GetString("San_Diego_Chargers_PHelmet2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Diego_Chargers5.jpg.
        '''</summary>
        Friend ReadOnly Property San_Diego_Chargers5Jpg() As String
            Get
                Return ResourceManager.GetString("San_Diego_Chargers5Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Francisco_49ers_PHelmet_New.jpg.
        '''</summary>
        Friend ReadOnly Property San_Francisco_49ers_PHelmet_NewJpg() As String
            Get
                Return ResourceManager.GetString("San_Francisco_49ers_PHelmet_NewJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Francisco_49ers04.jpg.
        '''</summary>
        Friend ReadOnly Property San_Francisco_49ers04Jpg() As String
            Get
                Return ResourceManager.GetString("San_Francisco_49ers04Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedule4GamesMax.txt.
        '''</summary>
        Friend ReadOnly Property Schedule4GamesMaxTxt() As String
            Get
                Return ResourceManager.GetString("Schedule4GamesMaxTxt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seattle_Seahawks_PHelmet_2012.jpg.
        '''</summary>
        Friend ReadOnly Property Seattle_Seahawks_PHelmet_2012Jpg() As String
            Get
                Return ResourceManager.GetString("Seattle_Seahawks_PHelmet_2012Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seattle_Seahawks2_2012.jpg.
        '''</summary>
        Friend ReadOnly Property Seattle_Seahawks2_2012Jpg() As String
            Get
                Return ResourceManager.GetString("Seattle_Seahawks2_2012Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SoldierField.jpg.
        '''</summary>
        Friend ReadOnly Property SoldierFieldJpg() As String
            Get
                Return ResourceManager.GetString("SoldierFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sports-Authority-Field.jpg.
        '''</summary>
        Friend ReadOnly Property SportsAuthorityFieldJpg() As String
            Get
                Return ResourceManager.GetString("SportsAuthorityFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SunLifeStadium.jpg.
        '''</summary>
        Friend ReadOnly Property SunLifeStadiumJpg() As String
            Get
                Return ResourceManager.GetString("SunLifeStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to superdome_saints.jpg.
        '''</summary>
        Friend ReadOnly Property Superdome_saintsJpg() As String
            Get
                Return ResourceManager.GetString("Superdome_saintsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tampa_Bay_Buccaneers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Tampa_Bay_Buccaneers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Tampa_Bay_Buccaneers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tampa_Bay_Buccaneers2.jpg.
        '''</summary>
        Friend ReadOnly Property Tampa_Bay_Buccaneers2Jpg() As String
            Get
                Return ResourceManager.GetString("Tampa_Bay_Buccaneers2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tennessee_Titans_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Tennessee_Titans_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Tennessee_Titans_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tennessee_Titans2.jpg.
        '''</summary>
        Friend ReadOnly Property Tennessee_Titans2Jpg() As String
            Get
                Return ResourceManager.GetString("Tennessee_Titans2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tennessee_Titans.jpg.
        '''</summary>
        Friend ReadOnly Property Tennessee_TitansJpg() As String
            Get
                Return ResourceManager.GetString("Tennessee_TitansJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to university_phoenix_stadium.jpg.
        '''</summary>
        Friend ReadOnly Property University_phoenix_stadiumJpg() As String
            Get
                Return ResourceManager.GetString("University_phoenix_stadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USBankStadium.jpg.
        '''</summary>
        Friend ReadOnly Property USBankStadiumJpg() As String
            Get
                Return ResourceManager.GetString("USBankStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Washington_Redskins_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Washington_Redskins_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Washington_Redskins_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Washington_Redskins2.jpg.
        '''</summary>
        Friend ReadOnly Property Washington_Redskins2Jpg() As String
            Get
                Return ResourceManager.GetString("Washington_Redskins2Jpg", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
