'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WPFFootball.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Francisco_49ers_PHelmet_New.jpg.
        '''</summary>
        Friend ReadOnly Property _49ers_PHelmet_NewJpg() As String
            Get
                Return ResourceManager.GetString("_49ers_PHelmet_NewJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Francisco_49ers04.jpg.
        '''</summary>
        Friend ReadOnly Property _49ers04Jpg() As String
            Get
                Return ResourceManager.GetString("_49ers04Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arizona_Cardinals.jpg.
        '''</summary>
        Friend ReadOnly Property Arizona_CardinalsJpg() As String
            Get
                Return ResourceManager.GetString("Arizona_CardinalsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArrowheadStadium.jpg.
        '''</summary>
        Friend ReadOnly Property ArrowheadStadiumJpg() As String
            Get
                Return ResourceManager.GetString("ArrowheadStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ATTStadium.jpg.
        '''</summary>
        Friend ReadOnly Property ATTStadiumJpg() As String
            Get
                Return ResourceManager.GetString("ATTStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BankOfAmericaStadium.jpg.
        '''</summary>
        Friend ReadOnly Property BankOfAmericaStadiumJpg() As String
            Get
                Return ResourceManager.GetString("BankOfAmericaStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chicago_Bears_PHelmet2.jpg.
        '''</summary>
        Friend ReadOnly Property Bears_PHelmet2Jpg() As String
            Get
                Return ResourceManager.GetString("Bears_PHelmet2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chicago_Bears4.jpg.
        '''</summary>
        Friend ReadOnly Property Bears4Jpg() As String
            Get
                Return ResourceManager.GetString("Bears4Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cincinnati_Bengals_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Bengals_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Bengals_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cincinnati_Bengals3.jpg.
        '''</summary>
        Friend ReadOnly Property Bengals3Jpg() As String
            Get
                Return ResourceManager.GetString("Bengals3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffalo_Bills_PHelmet_2011.jpg.
        '''</summary>
        Friend ReadOnly Property Bills_PHelmet_2011Jpg() As String
            Get
                Return ResourceManager.GetString("Bills_PHelmet_2011Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffalo_Bills02.jpg.
        '''</summary>
        Friend ReadOnly Property Bills02Jpg() As String
            Get
                Return ResourceManager.GetString("Bills02Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buffalo_Bills3.jpg.
        '''</summary>
        Friend ReadOnly Property Bills3Jpg() As String
            Get
                Return ResourceManager.GetString("Bills3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsFans2.Jpg.
        '''</summary>
        Friend ReadOnly Property BillsFans2Jpg() As String
            Get
                Return ResourceManager.GetString("BillsFans2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsFans3.Jpg.
        '''</summary>
        Friend ReadOnly Property BillsFans3Jpg() As String
            Get
                Return ResourceManager.GetString("BillsFans3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsFans.Jpg.
        '''</summary>
        Friend ReadOnly Property BillsFansJpg() As String
            Get
                Return ResourceManager.GetString("BillsFansJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsGreats.Jpg.
        '''</summary>
        Friend ReadOnly Property BillsGreatsJpg() As String
            Get
                Return ResourceManager.GetString("BillsGreatsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsLondon.Jpg.
        '''</summary>
        Friend ReadOnly Property BillsLondonJpg() As String
            Get
                Return ResourceManager.GetString("BillsLondonJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsMcCoy2.Jpg.
        '''</summary>
        Friend ReadOnly Property BillsMcCoy2Jpg() As String
            Get
                Return ResourceManager.GetString("BillsMcCoy2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsMcCoy.jpg.
        '''</summary>
        Friend ReadOnly Property BillsMcCoyJpg() As String
            Get
                Return ResourceManager.GetString("BillsMcCoyJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsOneBuffalo.jpg.
        '''</summary>
        Friend ReadOnly Property BillsOneBuffaloJpg() As String
            Get
                Return ResourceManager.GetString("BillsOneBuffaloJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsPassRush.jpg.
        '''</summary>
        Friend ReadOnly Property BillsPassRushJpg() As String
            Get
                Return ResourceManager.GetString("BillsPassRushJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsTaylor.jpg.
        '''</summary>
        Friend ReadOnly Property BillsTaylorJpg() As String
            Get
                Return ResourceManager.GetString("BillsTaylorJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BillsWatkinsTaylor.jpg.
        '''</summary>
        Friend ReadOnly Property BillsWatkinsTaylorJpg() As String
            Get
                Return ResourceManager.GetString("BillsWatkinsTaylorJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denver_Broncos_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Broncos_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Broncos_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Denver_Broncos2.jpg.
        '''</summary>
        Friend ReadOnly Property Broncos2Jpg() As String
            Get
                Return ResourceManager.GetString("Broncos2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleveland_Browns_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Browns_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Browns_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ClevelandBrowns2.jpg.
        '''</summary>
        Friend ReadOnly Property Browns21Jpg() As String
            Get
                Return ResourceManager.GetString("Browns21Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleveland_Browns2.jpg.
        '''</summary>
        Friend ReadOnly Property Browns2Jpg() As String
            Get
                Return ResourceManager.GetString("Browns2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleveland_Browns2.jpg.
        '''</summary>
        Friend ReadOnly Property Browns2Jpg1() As String
            Get
                Return ResourceManager.GetString("Browns2Jpg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tampa_Bay_Buccaneers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Buccaneers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Buccaneers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tampa_Bay_Buccaneers2.jpg.
        '''</summary>
        Friend ReadOnly Property Buccaneers2Jpg() As String
            Get
                Return ResourceManager.GetString("Buccaneers2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arizona_Cardinals_Helmet.jpg.
        '''</summary>
        Friend ReadOnly Property Cardinals_HelmetJpg() As String
            Get
                Return ResourceManager.GetString("Cardinals_HelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArizonaCardinals3.jpg.
        '''</summary>
        Friend ReadOnly Property Cardinals3Jpg() As String
            Get
                Return ResourceManager.GetString("Cardinals3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CenturyLinkField.jpg.
        '''</summary>
        Friend ReadOnly Property CenturyLinkFieldJpg() As String
            Get
                Return ResourceManager.GetString("CenturyLinkFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Diego_Chargers_PHelmet2.jpg.
        '''</summary>
        Friend ReadOnly Property Chargers_PHelmet2Jpg() As String
            Get
                Return ResourceManager.GetString("Chargers_PHelmet2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to San_Diego_Chargers5.jpg.
        '''</summary>
        Friend ReadOnly Property Chargers5Jpg() As String
            Get
                Return ResourceManager.GetString("Chargers5Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kansas_City_Chiefs_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Chiefs_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Chiefs_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kansas_City_Chiefs3.jpg.
        '''</summary>
        Friend ReadOnly Property Chiefs3Jpg() As String
            Get
                Return ResourceManager.GetString("Chiefs3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indianapolis_Colts_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Colts_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Colts_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indianapolis_Colts2.jpg.
        '''</summary>
        Friend ReadOnly Property Colts2Jpg() As String
            Get
                Return ResourceManager.GetString("Colts2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Indianapolis_Colts.jpg.
        '''</summary>
        Friend ReadOnly Property ColtsJpg() As String
            Get
                Return ResourceManager.GetString("ColtsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dallas_Cowboys_Phelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Cowboys_PhelmetJpg() As String
            Get
                Return ResourceManager.GetString("Cowboys_PhelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dallas_Cowboys3.jpg.
        '''</summary>
        Friend ReadOnly Property Cowboys3Jpg() As String
            Get
                Return ResourceManager.GetString("Cowboys3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miami_Dolphins_2013.jpg.
        '''</summary>
        Friend ReadOnly Property Dolphins_2013Jpg() As String
            Get
                Return ResourceManager.GetString("Dolphins_2013Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miami_Dolphins_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Dolphins_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Dolphins_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsCelebrate.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsCelebrateJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsCelebrateJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsGreats.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsGreatsJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsGreatsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsMiller.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsMillerJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsMillerJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsPreSnap.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsPreSnapJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsPreSnapJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsStadium.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsStadiumJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsTannehill.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsTannehillJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsTannehillJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DolphinsTrainingCamp.Jpg.
        '''</summary>
        Friend ReadOnly Property DolphinsTrainingCampJpg() As String
            Get
                Return ResourceManager.GetString("DolphinsTrainingCampJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Philadelphia_Eagles_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Eagles_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Eagles_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Philadelphia_Eagles2.jpg.
        '''</summary>
        Friend ReadOnly Property Eagles2Jpg() As String
            Get
                Return ResourceManager.GetString("Eagles2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EverBankField.jpg.
        '''</summary>
        Friend ReadOnly Property EverBankFieldJpg() As String
            Get
                Return ResourceManager.GetString("EverBankFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atlanta_Falcons_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Falcons_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Falcons_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Atlanta_Falcons.jpg.
        '''</summary>
        Friend ReadOnly Property FalconsJpg() As String
            Get
                Return ResourceManager.GetString("FalconsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fedex-field.jpg.
        '''</summary>
        Friend ReadOnly Property FedexFieldJpg() As String
            Get
                Return ResourceManager.GetString("FedexFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FirstEnergyStadium.jpg.
        '''</summary>
        Friend ReadOnly Property FirstEnergyStadiumJpg() As String
            Get
                Return ResourceManager.GetString("FirstEnergyStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to fordfield.jpg.
        '''</summary>
        Friend ReadOnly Property FordfieldJpg() As String
            Get
                Return ResourceManager.GetString("FordfieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Georgia-Dome.png.
        '''</summary>
        Friend ReadOnly Property GeorgiaDomePng() As String
            Get
                Return ResourceManager.GetString("GeorgiaDomePng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Giants_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Giants_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Giants_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Giants5.jpg.
        '''</summary>
        Friend ReadOnly Property Giants5Jpg() As String
            Get
                Return ResourceManager.GetString("Giants5Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gillette-stadium.jpg.
        '''</summary>
        Friend ReadOnly Property GilletteStadiumJpg() As String
            Get
                Return ResourceManager.GetString("GilletteStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FootballGoalLine.jpg.
        '''</summary>
        Friend ReadOnly Property GlobalClass_GetBackgroundFilePath_FootballGoalLine_jpg() As String
            Get
                Return ResourceManager.GetString("GlobalClass_GetBackgroundFilePath_FootballGoalLine_jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HeinzField.jpg.
        '''</summary>
        Friend ReadOnly Property HeinzFieldJpg() As String
            Get
                Return ResourceManager.GetString("HeinzFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jacksonville_Jaguars_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Jaguars_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Jaguars_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jacksonville_Jaguars2.jpg.
        '''</summary>
        Friend ReadOnly Property Jaguars2Jpg() As String
            Get
                Return ResourceManager.GetString("Jaguars2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Jets_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Jets_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Jets_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsDecker.jpg.
        '''</summary>
        Friend ReadOnly Property JetsDeckerJpg() As String
            Get
                Return ResourceManager.GetString("JetsDeckerJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsFans.jpg.
        '''</summary>
        Friend ReadOnly Property JetsFansJpg() As String
            Get
                Return ResourceManager.GetString("JetsFansJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsIvory.jpg.
        '''</summary>
        Friend ReadOnly Property JetsIvoryJpg() As String
            Get
                Return ResourceManager.GetString("JetsIvoryJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_York_Jets.jpg.
        '''</summary>
        Friend ReadOnly Property JetsJpg() As String
            Get
                Return ResourceManager.GetString("JetsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsMarshall.Jpg.
        '''</summary>
        Friend ReadOnly Property JetsMarshallJpg() As String
            Get
                Return ResourceManager.GetString("JetsMarshallJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsOverPile.jpg.
        '''</summary>
        Friend ReadOnly Property JetsOverPileJpg() As String
            Get
                Return ResourceManager.GetString("JetsOverPileJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsTouchdown2.jpg.
        '''</summary>
        Friend ReadOnly Property JetsTouchdown2Jpg() As String
            Get
                Return ResourceManager.GetString("JetsTouchdown2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsTunnel.jpg.
        '''</summary>
        Friend ReadOnly Property JetsTunnelJpg() As String
            Get
                Return ResourceManager.GetString("JetsTunnelJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JetsWallpaper.jpg.
        '''</summary>
        Friend ReadOnly Property JetsWallpaperJpg() As String
            Get
                Return ResourceManager.GetString("JetsWallpaperJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to lambeaufield.jpg.
        '''</summary>
        Friend ReadOnly Property LambeaufieldJpg() As String
            Get
                Return ResourceManager.GetString("LambeaufieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to levis-stadium.jpg.
        '''</summary>
        Friend ReadOnly Property LevisStadiumJpg() As String
            Get
                Return ResourceManager.GetString("LevisStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LincolnFinancialField.jpg.
        '''</summary>
        Friend ReadOnly Property LincolnFinancialFieldJpg() As String
            Get
                Return ResourceManager.GetString("LincolnFinancialFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detroit_Lions_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Lions_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Lions_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DetroitLions2.jpg.
        '''</summary>
        Friend ReadOnly Property Lions2Jpg() As String
            Get
                Return ResourceManager.GetString("Lions2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detroit_Lions3a.jpg.
        '''</summary>
        Friend ReadOnly Property Lions3aJpg() As String
            Get
                Return ResourceManager.GetString("Lions3aJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LosAngelesColiseum.jpg.
        '''</summary>
        Friend ReadOnly Property LosAngelesColiseumJpg() As String
            Get
                Return ResourceManager.GetString("LosAngelesColiseumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LucasOilStadium.jpg.
        '''</summary>
        Friend ReadOnly Property LucasOilStadiumJpg() As String
            Get
                Return ResourceManager.GetString("LucasOilStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MetLife_Stadium.jpg.
        '''</summary>
        Friend ReadOnly Property MetLife_StadiumJpg() As String
            Get
                Return ResourceManager.GetString("MetLife_StadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to M&amp;TBankStadium.jpg.
        '''</summary>
        Friend ReadOnly Property MTBankStadiumJpg() As String
            Get
                Return ResourceManager.GetString("MTBankStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NFLWallpaper2.jpg.
        '''</summary>
        Friend ReadOnly Property NFLWallpaper2Jpg() As String
            Get
                Return ResourceManager.GetString("NFLWallpaper2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NFLWallpaper.jpg.
        '''</summary>
        Friend ReadOnly Property NFLWallpaperJpg() As String
            Get
                Return ResourceManager.GetString("NFLWallpaperJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NissanStadium.jpg.
        '''</summary>
        Friend ReadOnly Property NissanStadiumJpg() As String
            Get
                Return ResourceManager.GetString("NissanStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NRGStadium.jpg.
        '''</summary>
        Friend ReadOnly Property NRGStadiumJpg() As String
            Get
                Return ResourceManager.GetString("NRGStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OaklandColiseum.jpg.
        '''</summary>
        Friend ReadOnly Property OaklandColiseumJpg() As String
            Get
                Return ResourceManager.GetString("OaklandColiseumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Green_Bay_Packers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Packers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Packers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Green_Bay_Packers5.jpg.
        '''</summary>
        Friend ReadOnly Property Packers5Jpg() As String
            Get
                Return ResourceManager.GetString("Packers5Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carolina_Panthers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Panthers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Panthers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carolina_Panthers2.jpg.
        '''</summary>
        Friend ReadOnly Property Panthers2Jpg() As String
            Get
                Return ResourceManager.GetString("Panthers2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carolina_Panthers.jpg.
        '''</summary>
        Friend ReadOnly Property PanthersJpg() As String
            Get
                Return ResourceManager.GetString("PanthersJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_England_Patriots_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Patriots_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Patriots_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_England_Patriots2.jpg.
        '''</summary>
        Friend ReadOnly Property Patriots2Jpg() As String
            Get
                Return ResourceManager.GetString("Patriots2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsBelichick.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsBelichickJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsBelichickJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsBradyGronk.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsBradyGronkJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsBradyGronkJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsBrady.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsBradyJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsBradyJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsCelebrate.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsCelebrateJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsCelebrateJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsDefense.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsDefenseJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsDefenseJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsEdelman.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsEdelmanJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsEdelmanJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsFans.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsFansJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsFansJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsGreats.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsGreatsJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsGreatsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsGronk.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsGronkJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsGronkJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsReceivers.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsReceiversJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsReceiversJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsSuperBowl.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsSuperBowlJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsSuperBowlJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PatriotsTunnel.jpg.
        '''</summary>
        Friend ReadOnly Property PatriotsTunnelJpg() As String
            Get
                Return ResourceManager.GetString("PatriotsTunnelJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PaulBrownStadium.jpg.
        '''</summary>
        Friend ReadOnly Property PaulBrownStadiumJpg() As String
            Get
                Return ResourceManager.GetString("PaulBrownStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QualcommStadium.jpg.
        '''</summary>
        Friend ReadOnly Property QualcommStadiumJpg() As String
            Get
                Return ResourceManager.GetString("QualcommStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oakland_Raiders_Helmet.jpg.
        '''</summary>
        Friend ReadOnly Property Raiders_HelmetJpg() As String
            Get
                Return ResourceManager.GetString("Raiders_HelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oakland_Raiders_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Raiders_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Raiders_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Oakland_Raiders.jpg.
        '''</summary>
        Friend ReadOnly Property RaidersJpg() As String
            Get
                Return ResourceManager.GetString("RaidersJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RalphWilsonStadium.jpg.
        '''</summary>
        Friend ReadOnly Property RalphWilsonStadiumJpg() As String
            Get
                Return ResourceManager.GetString("RalphWilsonStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LARams1.png.
        '''</summary>
        Friend ReadOnly Property Rams1Png() As String
            Get
                Return ResourceManager.GetString("Rams1Png", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LARams.jpg.
        '''</summary>
        Friend ReadOnly Property RamsJpg() As String
            Get
                Return ResourceManager.GetString("RamsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baltimore_Ravens_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Ravens_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Ravens_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baltimore_Ravens3.jpg.
        '''</summary>
        Friend ReadOnly Property Ravens3Jpg() As String
            Get
                Return ResourceManager.GetString("Ravens3Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RaymondJamesStadium.jpg.
        '''</summary>
        Friend ReadOnly Property RaymondJamesStadiumJpg() As String
            Get
                Return ResourceManager.GetString("RaymondJamesStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Washington_Redskins_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Redskins_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Redskins_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Washington_Redskins2.jpg.
        '''</summary>
        Friend ReadOnly Property Redskins2Jpg() As String
            Get
                Return ResourceManager.GetString("Redskins2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_Orleans_Saints_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Saints_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Saints_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_Orleans_Saints2.jpg.
        '''</summary>
        Friend ReadOnly Property Saints2Jpg() As String
            Get
                Return ResourceManager.GetString("Saints2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New_Orleans_Saints.jpg.
        '''</summary>
        Friend ReadOnly Property SaintsJpg() As String
            Get
                Return ResourceManager.GetString("SaintsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schedule4GamesMax.txt.
        '''</summary>
        Friend ReadOnly Property Schedule4GamesMaxTxt() As String
            Get
                Return ResourceManager.GetString("Schedule4GamesMaxTxt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seattle_Seahawks_PHelmet_2012.jpg.
        '''</summary>
        Friend ReadOnly Property Seahawks_PHelmet_2012Jpg() As String
            Get
                Return ResourceManager.GetString("Seahawks_PHelmet_2012Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seattle_Seahawks2_2012.jpg.
        '''</summary>
        Friend ReadOnly Property Seahawks2_2012Jpg() As String
            Get
                Return ResourceManager.GetString("Seahawks2_2012Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SoldierField.jpg.
        '''</summary>
        Friend ReadOnly Property SoldierFieldJpg() As String
            Get
                Return ResourceManager.GetString("SoldierFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sports-Authority-Field.jpg.
        '''</summary>
        Friend ReadOnly Property SportsAuthorityFieldJpg() As String
            Get
                Return ResourceManager.GetString("SportsAuthorityFieldJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pittsburgh_Steelers_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Steelers_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Steelers_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pittsburgh_Steelers2.jpg.
        '''</summary>
        Friend ReadOnly Property Steelers2Jpg() As String
            Get
                Return ResourceManager.GetString("Steelers2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pittsburgh_Steelers.jpg.
        '''</summary>
        Friend ReadOnly Property SteelersJpg() As String
            Get
                Return ResourceManager.GetString("SteelersJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SunLifeStadium.jpg.
        '''</summary>
        Friend ReadOnly Property SunLifeStadiumJpg() As String
            Get
                Return ResourceManager.GetString("SunLifeStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to superdome_saints.jpg.
        '''</summary>
        Friend ReadOnly Property Superdome_saintsJpg() As String
            Get
                Return ResourceManager.GetString("Superdome_saintsJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Houston_Texans_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Texans_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Texans_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Houston_Texans2.jpg.
        '''</summary>
        Friend ReadOnly Property Texans2Jpg() As String
            Get
                Return ResourceManager.GetString("Texans2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tennessee_Titans_PHelmet.jpg.
        '''</summary>
        Friend ReadOnly Property Titans_PHelmetJpg() As String
            Get
                Return ResourceManager.GetString("Titans_PHelmetJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tennessee_Titans2.jpg.
        '''</summary>
        Friend ReadOnly Property Titans2Jpg() As String
            Get
                Return ResourceManager.GetString("Titans2Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tennessee_Titans.jpg.
        '''</summary>
        Friend ReadOnly Property TitansJpg() As String
            Get
                Return ResourceManager.GetString("TitansJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to university_phoenix_stadium.jpg.
        '''</summary>
        Friend ReadOnly Property University_phoenix_stadiumJpg() As String
            Get
                Return ResourceManager.GetString("University_phoenix_stadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USBankStadium.jpg.
        '''</summary>
        Friend ReadOnly Property USBankStadiumJpg() As String
            Get
                Return ResourceManager.GetString("USBankStadiumJpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minnesota_Vikings_2013_06.jpg.
        '''</summary>
        Friend ReadOnly Property Vikings_2013_06Jpg() As String
            Get
                Return ResourceManager.GetString("Vikings_2013_06Jpg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minnesota_Vikings_PHelmet_2013.jpg.
        '''</summary>
        Friend ReadOnly Property Vikings_PHelmet_2013Jpg() As String
            Get
                Return ResourceManager.GetString("Vikings_PHelmet_2013Jpg", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
